force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Iniciada</fullName>
            </value>
            <value>
                <fullName>En Progreso</fullName>
            </value>
            <value>
                <fullName>Completada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/taskTableButtons.cls
public with sharing class taskTableButtons {
  @AuraEnabled(cacheable=false)
  public static Task__c changeTaskState(String taskIdStr, String newState) {
    Id taskId = Id.valueOf(taskIdStr);
    Task__c task = [SELECT State__c FROM Task__c WHERE Id = :taskId];
    task.State__c = newState;
    update task;
    return task;
    /*try {
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }*/
  }

  @AuraEnabled(cacheable=false)
  public static Task__c registerHours(String taskIdStr, Integer hours) {
    Id taskId = Id.valueOf(taskIdStr);
    try {
      Task__c task = [
        SELECT Id, Worked_Hours__c
        FROM Task__c
        WHERE Id = :taskId
      ];
      if (task.Worked_Hours__c != null) {
        task.Worked_Hours__c += hours;
      } else {
        task.Worked_Hours__c = hours;
      }
      update task;
      return task;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}