force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource / Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource / Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Rate_P_Hour__c.field-meta.xml
<CustomField>
    <fullName>Rate_P_Hour__c</fullName>
    <label>Rate P/Hour</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/roleResource.cls
public with sharing class roleResource {
    @AuraEnabled(cacheable=true)
    public static Map<string, List<user>> allRoleResource(String strRecordId){
        id recordId = Id.valueOf(strRecordId);
        //Fechas del Proyecto
        List<Project__c> fechas =[SELECT Start_Date__c, End_Date__c FROM Project__c WHERE Project__c.Id=: recordId ];

        //Listar recursos ocupados 
        // List<Resource_Project__c> recPro=[SELECT Resource__c, Project__r.Start_Date__c,Project__r.End_Date__c FROM Resource_Project__c WHERE star y end  dates entre fehcas del Porject];

        //Filtrar Recursos disponibles 

        List<user> recursos =[SELECT FirstName, LastName, userrole.name, Rate_P_Hour__c FROM user WHERE userrole.name != null ];

        
        Map<string, List<user>> recursosByRole = new Map<string, List<user>>();
        
        for (User u : recursos) {
            if (!recursosByRole.containsKey(u.userrole.name)) {
                recursosByRole.put(u.userrole.name,new List<user>());
            }
            recursosByRole.get(u.userrole.name).add(u);
        }
       return recursosByRole;
    }
}