force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/recordTypes/test.recordType-meta.xml
<RecordType>
    <fullName>test</fullName>
    <active>true</active>
    <label>test</label>
</RecordType>

force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>Project Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Line Items</relationshipLabel>
    <relationshipName>Projects_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/projectRolesTest.cls
@isTest
public with sharing class projectRolesTest {
  @isTest
  static void projectRolesTest() {
    Integer numOfProjects = 1;
    List<Project__c> projects = TestTaskDataFactory.createProjects(
      numOfProjects
    );
    List<String> newRoles = new List<String>{
      'Cyber Security',
      'terapeuta de LWC',
      'el que hace los test',
      'Oscar'
    };

    Test.startTest();
    List<Project_Line_Item__c> searchedPLI = projectRoles.allProjectRoles(
      projects.get(0).Id
    );
    System.assertEquals(4, searchedPLI.size(), 'trae todos los roles');
    Test.stopTest();
  }
}