force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick-off</fullName>
                <default>true</default>
                <label>Pre Kick-off</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource / Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource / Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/validateAllocationDates.cls
public with sharing class validateAllocationDates {
  //revisar si un resource project tiene las fechas superpuestas con otro
  public static Boolean checkValidDate(
    Resource_Project__c newRP,
    Resource_Project__c oldRP
  ) {
    if (
      newRp.Start_Date__c >= oldRP.Start_Date__c &&
      newRp.Start_Date__c <= oldRP.End_Date__c
    ) {
      return false;
    }
    if (
      newRp.End_Date__c >= oldRP.Start_Date__c &&
      newRp.End_Date__c <= oldRP.End_Date__c
    ) {
      return false;
    }
    return true;
  }

  public static List<Resource_Project__c> onInsert(
    List<Resource_Project__c> newresPros
  ) {
    //genero un set con las id de recursos
    Set<Id> resources = new Set<Id>();
    for (Resource_Project__c rp : newresPros) {
      resources.add(rp.Resource__c);
    }
    //traigo todos sus Resource_Project__c
    List<Resource_Project__c> allResProsSchedules = [
      SELECT Resource__c, Start_Date__c, End_Date__c, Project__r.Status__c
      FROM Resource_Project__c
      WHERE Resource__c IN :resources AND Project__r.Status__c = 'In Progress'
    ];
    //genero un mata key:Resource__c.Id, value: lista de sus resource_Project__c
    Map<Id, List<Resource_Project__c>> scheduledDatesByResource = new Map<Id, List<Resource_Project__c>>();
    for (Resource_Project__c rp : allResProsSchedules) {
      if (scheduledDatesByResource.containsKey(rp.Resource__c)) {
        scheduledDatesByResource.get(rp.Resource__c).add(rp);
      } else {
        scheduledDatesByResource.put(
          rp.Resource__c,
          new List<Resource_Project__c>{ rp }
        );
      }
    }
    //reviso cada RP ingresante con sus RP ya existentes, los invalidos serán retornados
    List<Resource_Project__c> invalidResourceProjects = new List<Resource_Project__c>();
    for (Resource_Project__c newRP : newresPros) {
      if (scheduledDatesByResource.containsKey(newRP.Resource__c)) {
        for (
          Resource_Project__c rp : scheduledDatesByResource.get(
            newRP.Resource__c
          )
        ) {
          if (!validateAllocationDates.checkValidDate(newRP, rp)) {
            invalidResourceProjects.add(newRP);
          }
        }
      }
    }
    return invalidResourceProjects;
  }

  public static List<Resource_Project__c> onUpdate(
    List<Resource_Project__c> oldRespros,
    List<Resource_Project__c> newResPros
  ) {
    //genero 2 sets con las ids de los viejos y nuevos RP
    Set<Id> resources = new Set<Id>();
    Set<Id> oldResources = new Set<Id>();
    for (Integer indexRP = 0; indexRP < newResPros.size(); indexRP++) {
      resources.add(newResPros.get(indexRP).Resource__c);
      oldResources.add(oldRespros.get(indexRP).Resource__c);
    }
    //traigo los resource project relacionados por usuario
    List<Resource_Project__c> allResProsSchedules = [
      SELECT Resource__c, Start_Date__c, End_Date__c, Project__r.Status__c
      FROM Resource_Project__c
      WHERE Resource__c IN :resources AND Project__r.Status__c = 'In Progress'
    ];
    //vinculo los resource project en un mapa, con el Resource__c como key
    //ignorando los viejos valores en la actualización
    Map<Id, List<Resource_Project__c>> scheduledDatesByResource = new Map<Id, List<Resource_Project__c>>();
    for (Resource_Project__c rp : allResProsSchedules) {
      if (oldResources.contains(rp.Id)) {
        //evita que al actualizar, no se compare la fecha con la version antertior
        continue;
      }
      if (scheduledDatesByResource.containsKey(rp.Resource__c)) {
        scheduledDatesByResource.get(rp.Resource__c).add(rp);
      } else {
        scheduledDatesByResource.put(
          rp.Resource__c,
          new List<Resource_Project__c>{ rp }
        );
      }
    }
    //reviso cada RP ingresante con sus RP ya existentes, retornando los invalidos
    List<Resource_Project__c> invalidResourceProjects = new List<Resource_Project__c>();
    for (Resource_Project__c newRP : newresPros) {
      if (scheduledDatesByResource.containsKey(newRP.Resource__c)) {
        for (
          Resource_Project__c rp : scheduledDatesByResource.get(
            newRP.Resource__c
          )
        ) {
          if (!validateAllocationDates.checkValidDate(newRP, rp)) {
            invalidResourceProjects.add(newRP);
          }
        }
      }
    }
    return invalidResourceProjects;
  }
}