force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/recordTypes/test.recordType-meta.xml
<RecordType>
    <fullName>test</fullName>
    <active>true</active>
    <label>test</label>
</RecordType>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource / Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource / Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/roleResourceTest.cls
@isTest
public with sharing class roleResourceTest {
  @isTest
  static void findsAllResources() {
    Integer numOfProjects = 1;
    Integer numOfResources = 10;
    List<Project__c> projects = TestTaskDataFactory.createProjects(
      numOfProjects
    );
    List<User> resources = TestTaskDataFactory.createBulkUsers(
      projects,
      numOfResources
    );
    List<Resource_Project__c> resPros = TestTaskDataFactory.createResourceProjects(
      projects,
      resources,
      numOfResources
    );
    Test.startTest();
    Map<String, List<user>> ResourcesByRole = roleResource.allRoleResource(
      projects.get(0).Id
    );
    System.assertEquals(
      10,
      ResourcesByRole.get('Arquitecto').size(),
      'encuentra a todos los usuarios'
    );

    Test.stopTest();
  }
}