force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>Project Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Line Items</relationshipLabel>
    <relationshipName>Projects_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arquitecto</fullName>
            </value>
            <value>
                <fullName>Consultor</fullName>
            </value>
            <value>
                <fullName>Desarrollador</fullName>
            </value>
            <value>
                <fullName>Project_Manager</fullName>
                <label>Project Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Sold_Role_Hours__c.field-meta.xml
<CustomField>
    <fullName>Sold_Role_Hours__c</fullName>
    <label>Sold Role Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/projectRoles.cls
public with sharing class projectRoles {
  @AuraEnabled(cacheable=false)
  public static List<Project_Line_Item__c> allProjectRoles(String strRecordId) {
    id recordId = Id.valueOf(strRecordId);
    List<Project_Line_Item__c> allProjectRoles = [
      SELECT Role__c, Sold_Role_Hours__c
      FROM Project_Line_Item__c
      WHERE Project__r.id = :recordId
      ORDER BY Role__c ASC
    ];

    return allProjectRoles;
  }
}