force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/recordTypes/test.recordType-meta.xml
<RecordType>
    <fullName>test</fullName>
    <active>true</active>
    <label>test</label>
</RecordType>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource / Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource / Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Resource_Project__c.field-meta.xml
<CustomField>
    <fullName>Resource_Project__c</fullName>
    <label>Resource Project</label>
    <referenceTo>Resource_Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/getTasksInProgressTest.cls
@isTest
public with sharing class getTasksInProgressTest {
    @isTest static void getsTheTasks() {
        Integer numOfProjects = 1;
        Integer numOfResources = 1;
        Integer numOfTasks = 2;
        List<Project__c> projects = TestTaskDataFactory.createProjects(numOfProjects);
        List<User> resources = TestTaskDataFactory.createBulkUsers(projects, numOfResources);
        List<Resource_Project__c> resPros = TestTaskDataFactory.createResourceProjects(projects, resources, numOfResources);
        List<Task__c> tasks = TestTaskDataFactory.createTasks(resPros, numOfTasks);
        User res = resources.get(0);
        Resource_Project__c resPro = resPros.get(0);
        Project__c project = [SELECT Id, Name FROM Project__c WHERE Id =: resPro.Project__c];
        
        Test.startTest();
        Map<String, List<Task__c>> testTasks = getTasksInProgress.getResourceTasks(resPro.Resource__c);
        System.assertEquals(1, testTasks.size(), 'Encontró el proyecto');
        System.assertEquals(2, testTasks.get(project.Name).size(), 'Encontró las tareas');
        test.stopTest();
    }
    @isTest static void withMultipleProjects(){
        Integer numOfProjects = 2;
        Integer numOfResources = 1;
        Integer numOfTasks = 5;
        List<Project__c> projects = TestTaskDataFactory.createProjects(numOfProjects);
        List<User> resources = TestTaskDataFactory.createBulkUsers(projects, numOfResources);
        List<User> sameResource = new List<User>{resources.get(0), resources.get(0)};
        List<Resource_Project__c> resPros = TestTaskDataFactory.createResourceProjects(projects, sameResource, numOfResources);
        List<Task__c> tasks = TestTaskDataFactory.createTasks(resPros, numOfTasks);

        Resource_Project__c resPro = resPros.get(0);
        Resource_Project__c resPro2 = resPros.get(1);

        List<Project__c> project = [SELECT Id, Name FROM Project__c WHERE Id =: resPro.Project__c OR Id =: resPro2.Project__c];
        Test.startTest();
        Map<String, List<Task__c>> testTasks = getTasksInProgress.getResourceTasks(resPro.Resource__c);
        System.assertEquals(2, testTasks.size(), 'Encontró el proyecto');
        System.assertEquals(5, testTasks.get(project.get(0).Name).size(), 'Encontró las tareas');
        test.stopTest();
    }
}