force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource / Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource / Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Worked_Hours__c.field-meta.xml
<CustomField>
    <fullName>Worked_Hours__c</fullName>
    <label>Worked Hours</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Quantity_Hours__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Hours__c</fullName>
    <label>Quantity Hours</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Resource_Project__c.field-meta.xml
<CustomField>
    <fullName>Resource_Project__c</fullName>
    <label>Resource Project</label>
    <referenceTo>Resource_Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Iniciada</fullName>
            </value>
            <value>
                <fullName>En Progreso</fullName>
            </value>
            <value>
                <fullName>Completada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getTasksInProgress.cls
public with sharing class getTasksInProgress {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<Task__c>> getResourceTasks(Id ResourceId) {
        /*
        Se consigue un mapa de nombres de proyectos con la Id del resource_Project como key
        y una lista de todas las tareas del recurso
        */
        Map<Id, Resource_Project__c> ProjectNamesByResourceProjectId = new Map<Id, Resource_Project__c>([SELECT Id, Project__r.Name FROM Resource_Project__c WHERE  Resource__c =: ResourceId]);
        List<Task__c> resourceTasks = [
            SELECT 
                Name, 
                State__c, 
                Quantity_Hours__c, 
                Worked_Hours__c,
                Resource_Project__c
            FROM Task__c
            WHERE Resource_Project__c in: ProjectNamesByResourceProjectId.keySet()
        ];
        //se agrupan todas las tareas por proyecto en un mapa y se retorna ese mapa
        Map<String, List<Task__c>> tasksByProjectName = new Map<String, List<Task__c>>();
        for(Task__c task : resourceTasks){
            String ProjectName = ProjectNamesByResourceProjectId.get(task.Resource_Project__c).Project__r.Name;
            if(TasksByProjectName.containsKey(ProjectName)){
                TasksByProjectName.get(ProjectName).add(task);
            }
            else{
                TasksByProjectName.put(ProjectName, new List<Task__c>{task});
            }
        }
        return tasksByProjectName;
    }
}